config/routes.rb
Rails.application.routes.draw do
  devise_for :users  
  resources :users do
    member do
      get :following, :followers
    end
    resources :posts do
      resources :comments
    end  
  end
  resources :friendships, only: %i[create destroy]
  get 'users' => 'users#index', as: 'user_root'
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :firstname, presence: true
  validates :lastname, presence: true
  # Add avatar
  has_one_attached :avatar
  
  # Posts
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy  
  # Follower's 
  has_many :active_friendships, class_name: 'Friendship', foreign_key: 'follower_id',
    dependent: :destroy

  has_many :passive_friendships, class_name: 'Friendship', foreign_key: 'followed_id',
    dependent: :destroy
      
  has_many :following, through: :active_friendships,  source: :followed
  has_many :followers, through: :passive_friendships, source: :follower

  def follow(user)
    active_friendships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end  

  def following?(user)
    following.include?(user)
  end  
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
   def cancel
     super
   end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  #  def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname]) 
  #  # devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password, :password_confirmation) }
  #  end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:firstname, :lastname, :email, :password, :current_password) }
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :owner?, only: %i[edit destroy]
  def index
    @users = User.all
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  # def new
  #   @user = User.new
  # end

  def edit
    @user = User.find(params[:id])
  end

  #def create
  #  @user = User.new(user_params)
  #  if @user.save
  #    redirect_to @user
  #  else
  #    render 'new'
  #  end
  #end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy    
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :avatar)
  end

  
  def owner?
    unless current_user.id == User.find(params[:id]) || !current_user.nil?  
      redirect_back fallback_location: root_path, notice: 'User is not owner'
    end

  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
    <h2>
       <%= pluralize(@user.errors.count, "error") %> prohibited
       this user from being saved:
     </h2>
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
     </div>
<% end %>
<p>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</p>
<p>
  <%= form.label :firstname %><br>
  <%= form.text_field :firstname %>
</p>
<p>
  <%= form.label :lastname %><br>
  <%= form.text_field :lastname %>
</p>
<p>
  <%= form.submit %>
</p>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <%= link_to 'Back', users_path, :class => "nav-link" %>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
            <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.firstname %></p>
            <p class="change-photo">Main settings</p>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :lastname, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :lastname, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :firstname, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :firstname, class: 'form-control' %>
          </div>
        </div>
      
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div style="text-align:center">
<h1>Users</h1>

<table>
  <tr>
    <th>User ID</th>
    <th>Email</th>
    <th>Functions</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.id  %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_path(user) %> 
      
      
      <% if owner?(user)  %>
      <%= link_to 'Edit', edit_user_path(user) %>
      <%= link_to 'Destroy', user_path(user),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
      <% end %>
        
      </td>
    </tr>
  <% end %>
</table>  
</div>

app/views/users/new.html.erb
<h2>User Registration</h2>
<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="user-profile">
<%flash.each do |key, value|%>
  <%= content_tag :div,value, class:"alert alert-warning"%>
<%end%>
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar %>
        <%end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.email %></h2>
        <% if @user == current_user %>
          <a class="edit-profile" href="<%= edit_user_path(@user) %>">
            <button>Edit Profile</button>
          </a>
        <% end %>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span><%= @user.followers.count%></span> followers</li>
        <li><span><%= @user.following.count%></span> following</li>
      </ul>
      <h2 class="name"><%=@user.firstname %></h2>
    <% if current_user!=@user %>
      <% if current_user.following?(@user) %>
      <%= link_to 'Unfollow', friendship_path(user_id: @user.id), method: :delete, :class => "btn btn-primary" %>
      <% else %>
      <%= link_to 'Follow', friendships_path(user_id: @user.id), method: :post, :class => "btn btn-primary" %>
      <% end %>
    <% end %>  
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" data-toggle="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>


  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to user_post_path(@user.id,post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
 
 <% if  @user.following.count != 0%>
  <h3>Followings: </h3> 
 <% else %>
  <h3>Followings on the way!</h3> 
 <% end %>
 
 <div class='homepage'>
<% @user.following.count do |follower|%>
  <br>
  <div class="posts">
  <% follower.posts.count do |fp| %>
      <%= render partial: 'home/post', locals: { post: fp } %>
  <%end%>
  </div>
     

<% end %>
</div>
<%= link_to 'Back', users_path, :class => "btn btn-primary" %>
  
  
    
      

</div>